export { Alt1CompactList } from './Alt1CompactList';
export { Alt2MinimalGrid } from './Alt2MinimalGrid';
export { Alt3DarkMode } from './Alt3DarkMode';
export { Alt4Carousel } from './Alt4Carousel';
export { Alt5BubbleLayout } from './Alt5BubbleLayout';
export { Alt6Magazine } from './Alt6Magazine';
export { Alt7AppStore } from './Alt7AppStore';
export { Alt8RetroArcade } from './Alt8RetroArcade';
export { Alt9FlatMaterial } from './Alt9FlatMaterial';
export { Alt10SidebarCategories } from './Alt10SidebarCategories';
export type { GameSelectorAltProps } from './types';
